version: '3'
services:
    postgres:
      container_name: postgres
      ports:
        - "5432:5432"
      image: library/postgres:10.13
      restart: unless-stopped

      environment:
        - "LC_ALL=C.UTF-8"
        - "POSTGRES_DB=dvndb"
        - "POSTGRES_USER=dvnuser"
        - "POSTGRES_PASSWORD=dvnsecret"
        - "POSTGRES_PORT=5432"
      volumes:
        - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

    solr:
      image: ekoindarto/solr-cvm:latest
      container_name: solr
      privileged: true
      ports:
        - "8983:8983"
      environment:
        - "SOLR_HOST=solr"
        - "SOLR_PORT=8983"
        - "SOLR_JAVA_MEM=-Xms1g -Xmx1g"
      volumes:
        - solr-data:/opt/solr/server/solr/collection1/data

    dataverse:
        image: ekoindarto/dataverse-cvm:5.0
        container_name: dataverse
        privileged: true
        ports:
        - "443:443"
        - "8080:8080"
        - "4848:4848"
        environment:
          - "CVM_SERVER_NAME=CESSDA" #Optional
          - "CVM_SERVER_URL=https://cvm.dataverse.tk" #Optional
          - "CVM_TSV_SOURCE=https://raw.githubusercontent.com/ekoi/speeltuin/master/resources/CMM_Custom_MetadataBlock.tsv" #Optional
          - "WAR_FILE=https://github.com/IQSS/dataverse-docker/releases/download/5.0.1-cvm/dataverse-5_0_cvm.war"
          - "HOST_DNS_ADDRESS=0.0.0.0"
          - "LANG=en"
          - "BUNDLEPROPERTIES=Bundle.properties"
          - "ADMIN_EMAIL=admin@localhost"
          - "MAIL_SERVER=mailrelay"
          - "POSTGRES_SERVER=postgres"
          - "POSTGRES_PORT=5432"
          - "POSTGRES_DATABASE=dvndb"
          - "POSTGRES_USER=dvnuser"
          - "PGPASSWORD=dvnsecret"
          - "SOLR_LOCATION=solr:8983"
          - "TWORAVENS_LOCATION=NOT INSTALLED"
          - "RSERVE_HOST=localhost"
          - "RSERVE_PORT=6311"
          - "RSERVE_USER=rserve"
          - "RSERVE_PASSWORD=rserve"
          - "JVM_OPTS='-Xmx1g -Xms1g -XX:MaxPermSize=2g -XX:PermSize=2g'"
        depends_on:
          - postgres
          - solr
        volumes:
          - dataverse-data:/usr/local/payara5/glassfish/domains/domain1/autodeploy
volumes:
  database-data:
  solr-data:
  dataverse-data:

networks:
  dvn:
    driver: bridge

